### ISSUE TITLE
Agregar SatoshiTango

### ISSUE THREAD

**Issue by isvillanuevap** [LeoSalgadoA/Mercado-Cripto#1]
Estimados,
Les comparto el link con el ticker en CLP de SatoshiTango. Lo único que tenemos público por el momento: https://api.satoshitango.com/v3/ticker/CLP

Saludos!
Sebastián Villanueva
Country Manager SatoshiTango Chile

**Comment by LeoSalgadoA** [comment]
Hermoso con esto tengo suficiente, estamos migrando a algo mas "escalable", tiene algun limite esa api? para no pasarme de request por minuto o por dia?

Saludos.

**Comment by LeoSalgadoA** [comment]
Done!

**Comment by LeoSalgadoA** [comment]
https://mercado-cripto.herokuapp.com/

**Comment by isvillanuevap** [comment]
5 Request por minuto. Si el precio cambia, lo hace cada 30 segundos.
